---
- name: Provision Lima VMs
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars_files:
    - "../../{{ config_file | default('vars/cluster_config.yml') }}"
  
  vars:
    disk_prefix: "minio"
  
  tasks:
    - name: Override cluster name if specified
      ansible.builtin.set_fact:
        kubernetes_cluster: "{{ kubernetes_cluster | combine({'name': cluster_name_override}) }}"
      when: cluster_name_override is defined

    - name: Get current user
      ansible.builtin.command: whoami
      register: current_user
      changed_when: false
      check_mode: false

    - name: Generate Lima VM configuration files
      ansible.builtin.template:
        src: ../../templates/lima_vm.yml.j2
        dest: "/tmp/{{ kubernetes_cluster.name }}-{{ vm.name }}.yaml"
        mode: '0644'
      loop: "{{ kubernetes_cluster.nodes }}"
      loop_control:
        loop_var: vm
        index_var: vm_index
    
    - name: Start Lima VMs
      ansible.builtin.shell: |
        limactl start --name={{ kubernetes_cluster.name }}-{{ vm.name }} /tmp/{{ kubernetes_cluster.name }}-{{ vm.name }}.yaml
      args:
        creates: "{{ ansible_env.HOME }}/.lima/{{ kubernetes_cluster.name }}-{{ vm.name }}"
      loop: "{{ kubernetes_cluster.nodes }}"
      loop_control:
        loop_var: vm
      register: lima_vm_start
      when: not ansible_check_mode
      
    - name: Display VM creation status
      ansible.builtin.debug:
        msg: "{{ kubernetes_cluster.name }}-{{ item.vm.name }}: {{ 'Created' if item.changed else 'Already exists' }}"
      loop: "{{ lima_vm_start.results }}"
      loop_control:
        label: "{{ kubernetes_cluster.name }}-{{ item.vm.name }}"
      when: lima_vm_start is defined and not ansible_check_mode
    
    - name: Display check mode message
      ansible.builtin.debug:
        msg: "Check mode: Would start {{ kubernetes_cluster.nodes | length }} Lima VMs"
      when: ansible_check_mode
    
    - name: Wait for VMs to be ready
      ansible.builtin.pause:
        seconds: 30
        prompt: "Waiting for VMs to initialize..."
      when: lima_vm_start is defined and lima_vm_start.changed and not ansible_check_mode
    
    - name: Create inventory directory
      ansible.builtin.file:
        path: "{{ playbook_dir }}/inventory"
        state: directory
        mode: '0755'
    
    - name: Generate inventory file
      ansible.builtin.template:
        src: ../../templates/inventory.ini.j2
        dest: "{{ playbook_dir }}/inventory/{{ kubernetes_cluster.name }}.ini"
        mode: '0644'
      
    - name: Display inventory location
      ansible.builtin.debug:
        msg: "Inventory file generated at: {{ playbook_dir }}/inventory/{{ kubernetes_cluster.name }}.ini"