---
- name: Install and configure DirectPV
  hosts: "{{ target_cluster | default('demo-k8s') }}_control_plane[0]"
  gather_facts: no
  become: no
  
  vars_files:
    - ../../vars/cluster_config.yml
  
  vars:
    kubeconfig_path: "{{ ansible_user_dir }}/.kube/config"
  
  tasks:
    - name: Install DirectPV plugin via krew
      ansible.builtin.shell: |
        kubectl krew install directpv
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.krew/bin"
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: directpv_plugin_install
      changed_when: "'installed' in directpv_plugin_install.stdout"
      failed_when: 
        - directpv_plugin_install.rc != 0
        - "'already installed' not in directpv_plugin_install.stderr"
    
    - name: Install DirectPV on cluster
      ansible.builtin.shell: |
        kubectl directpv install --node-selector directpv=yes
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.krew/bin"
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: directpv_install
      changed_when: "'created' in directpv_install.stdout or 'configured' in directpv_install.stdout"
    
    - name: Wait for DirectPV to be ready
      ansible.builtin.shell: |
        kubectl wait --for=condition=available --timeout=300s deployment/directpv-controller -n directpv
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
    
    - name: Discover available drives
      ansible.builtin.shell: |
        kubectl directpv discover --output-file={{ ansible_user_dir }}/drives.yaml
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.krew/bin"
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: directpv_discover
      changed_when: true
    
    - name: Display discovered drives
      ansible.builtin.shell: |
        cat {{ ansible_user_dir }}/drives.yaml
      register: drives_content
      changed_when: false
    
    - name: Show discovered drives
      ansible.builtin.debug:
        msg: "{{ drives_content.stdout_lines }}"
    
    - name: "Initialize drives (WARNING: This will format drives!)"
      ansible.builtin.shell: |
        kubectl directpv init --dangerous {{ ansible_user_dir }}/drives.yaml
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.krew/bin"
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: directpv_init
      changed_when: "'initialized' in directpv_init.stdout"
      when: auto_initialize_drives | default(false) | bool
    
    - name: Manual drive initialization message
      ansible.builtin.debug:
        msg: |
          IMPORTANT: DirectPV drives discovered but not initialized.
          
          To manually initialize drives, run:
          kubectl directpv init --dangerous {{ ansible_user_dir }}/drives.yaml
          
          Or set 'auto_initialize_drives: true' in your configuration.
          
          WARNING: This will format all discovered drives!
      when: not (auto_initialize_drives | default(false) | bool)
    
    - name: Check DirectPV status
      ansible.builtin.shell: |
        kubectl directpv info
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.krew/bin"
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: directpv_status
      changed_when: false
    
    - name: Display DirectPV status
      ansible.builtin.debug:
        msg: "{{ directpv_status.stdout_lines }}"