---
- name: Install K3s on control plane nodes
  hosts: "{{ target_cluster | default('demo-k8s') }}_control_plane"
  gather_facts: yes
  become: yes
  
  vars_files:
    - ../../vars/cluster_config.yml
  
  tasks:
    - name: Download K3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: '0755'
    
    - name: Install K3s server
      ansible.builtin.shell: |
        INSTALL_K3S_EXEC="--disable traefik" /tmp/k3s-install.sh
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version | default('') }}"
      register: k3s_install_result
      changed_when: "'systemd' in k3s_install_result.stdout"
    
    - name: Wait for K3s to be ready
      ansible.builtin.wait_for:
        port: 6443
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 300
    
    - name: Get node token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token
    
    - name: Set node token fact
      ansible.builtin.set_fact:
        k3s_node_token: "{{ node_token.content | b64decode | trim }}"

- name: Install K3s on worker nodes
  hosts: "{{ target_cluster | default('demo-k8s') }}_workers"
  gather_facts: yes
  become: yes
  
  vars_files:
    - ../../vars/cluster_config.yml
  
  tasks:
    - name: Download K3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: '0755'
    
    - name: Install K3s agent
      ansible.builtin.shell: |
        /tmp/k3s-install.sh
      environment:
        K3S_URL: "https://{{ hostvars[groups[target_cluster + '_control_plane'][0]]['ansible_default_ipv4']['address'] }}:6443"
        K3S_TOKEN: "{{ hostvars[groups[target_cluster + '_control_plane'][0]]['k3s_node_token'] }}"
        INSTALL_K3S_VERSION: "{{ k3s_version | default('') }}"
      register: k3s_agent_install_result
      changed_when: "'systemd' in k3s_agent_install_result.stdout"

- name: Configure kubectl access
  hosts: "{{ target_cluster | default('demo-k8s') }}_control_plane[0]"
  gather_facts: yes
  become: no
  
  vars_files:
    - ../../vars/cluster_config.yml
  
  tasks:
    - name: Create .kube directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.kube"
        state: directory
        mode: '0755'
    
    - name: Copy kubeconfig
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ ansible_user_dir }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
        remote_src: yes
      become: yes
    
    - name: Update kubeconfig server address
      ansible.builtin.replace:
        path: "{{ ansible_user_dir }}/.kube/config"
        regexp: 'https://127\.0\.0\.1:6443'
        replace: "https://{{ ansible_default_ipv4.address }}:6443"
    
    - name: Fetch kubeconfig to local machine
      ansible.builtin.fetch:
        src: "{{ ansible_user_dir }}/.kube/config"
        dest: "./kubeconfig-{{ kubernetes_cluster.name }}"
        flat: yes

- name: Label nodes for storage
  hosts: "{{ target_cluster | default('demo-k8s') }}_control_plane[0]"
  gather_facts: no
  become: no
  
  vars_files:
    - ../../vars/cluster_config.yml
  
  tasks:
    - name: Label worker nodes for DirectPV
      ansible.builtin.shell: |
        kubectl label node {{ item }} directpv=yes --overwrite
      loop: "{{ groups[target_cluster + '_workers'] }}"
      environment:
        KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"
      register: label_result
      changed_when: "'labeled' in label_result.stdout"
    
    - name: Taint control plane node
      ansible.builtin.shell: |
        kubectl taint node {{ inventory_hostname }} node-role.kubernetes.io/control-plane:NoSchedule --overwrite
      environment:
        KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"
      register: taint_result
      changed_when: "'tainted' in taint_result.stdout or 'updated' in taint_result.stdout"
      failed_when: 
        - taint_result.rc != 0
        - "'already has a taint' not in taint_result.stderr"